name: Autoupdate

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Existing version tag to publish'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Run CI/CD Pipeline
        uses: zource-dev/action@v2
        with:
          release_tag: ${{ inputs.release_tag }}
          node_version: '22.23.3'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          autoupdate: minor
          username: Ivan Zakharchanka
          email: 3axap4eHko@github.com
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          test: |
            pnpm test
            pnpm test:build
